### ISSUE TITLE
Investigate if Ollama supports OpenAI API schema

### ISSUE THREAD

**Issue by nqngo** [bifrostlab/deploy-llm-bot#1]
Ollama is one of the easiest method to deploy a LLM model with NVIDIA GPU support.

Investigate if Ollama supports OpenAI API Schema. This is to ensure that our LLM bot can use both OpenAI and the local LLM model.

If it cannot support OpenAI schema, could you identify another application that can supplement or replace Ollama? It must be a Docker image with minimal configuration.

**Comment by phattantran1997** [comment]
I see 1 blog talk about extending Ollama with OpenAI API: https://jensenlwt.io/extending-ollama-leverage-the-power-of-ollama-and-litellm-for-openai-compatibility?ref=dailydev ( Hopefully it can help)

**Comment by hungdtrn** [comment]
It is possible to combine Ollama with Litellm for OpenAI Compatibility
Link: [here](https://jensenlwt.io/extending-ollama-leverage-the-power-of-ollama-and-litellm-for-openai-compatibility)

**Comment by nqngo** [comment]
Can we package that into a docker image?

**Comment by hungdtrn** [comment]
I think yes.
Litellm does not affect Ollama, it provide an Open Ai interface for us to interact with Ollama.
We setup the docker image of Ollama as normal.

**Comment by phattantran1997** [comment]
On the LiteLLM official site, we can use a docker image for it. But confused about whether we use a LiteLLM proxy that will execute both Ollama models and OpenAI API together, right?

**Comment by hungdtrn** [comment]
@phattantran1997  No, we LiteLLM has nothing to do with OpenAI. It is a proxy server that allow us to interact with Ollama the same way we interact with OpenAI APIs

On the docker of Ollama, we have Ollama run at the default port, then we set up LiteLLM as the proxy server at a different port (e.g; port 8000). Then we direct our request to this port, with the same parameters we use for OpenAI APIs.

**Comment by hungdtrn** [comment]
@phattantran1997  Actually, that is a good idea. We can setup litellm to create a proxy server that wrap around both OpenAPI models and Ollama models, then use OpenAI SDK to interact with our proxy server.

I updated the document and the code, please have a look/
